# This workflow runs tests using node and then publishes a package to GitHub Packages
# whenever a release is created, and it's tag starts with "2"
# The pipeline is aimed on "v2" branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package v2

on:
  release:
    types: [published]
    tags:
      - '2*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'v2'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
